---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: &app opnsense-backup
  namespace: default
spec:
  schedule: "@daily"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      template:
        spec:
          automountServiceAccountToken: false
          restartPolicy: Never
          containers:
            - name: *app
              image: ghcr.io/onedr0p/kubernetes-kubectl:1.27.3@sha256:fcc5372b0e1e3d51c0d3a95282fdfd80aeb389aa4077fd430276c511857313cf
              env:
                - name: OPNSENSE_URL
                  value: "http://opnsense.${PRIVATE_SECRET_DOMAIN}"
                - name: S3_URL
                  value: "http://minio.default.svc.cluster.local:9000"
              envFrom:
                - secretRef:
                    name: *app
              command:
                - "/bin/bash"
                - &scriptPath "/app/opnsense-backup.sh"
              volumeMounts:
                - name: *app
                  mountPath: *scriptPath
                  subPath: &scriptName opnsense-backup.sh
                  readOnly: true
          volumes:
            - name: *app
              projected:
                defaultMode: 0775
                sources:
                  - configMap:
                      name: *app
                      items:
                        - key: *scriptName
                          path: *scriptName
