---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: &name plex-off-deck
  namespace: default
spec:
  schedule: "@hourly"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600
      template:
        spec:
          automountServiceAccountToken: false
          restartPolicy: OnFailure
          containers:
            - name: off-deck
              image: ghcr.io/onedr0p/jbops:1.0.893@sha256:eb8b245e79bae07ec6b00044a95269e1f2e97005cd704ad9d77a0b31c5f28894
              env:
                - name: TZ
                  value: "${TIMEZONE}"
                - name: JBOPS__SCRIPT_PATH
                  value: utility/off_deck.py
              args:
                - /entrypoint.sh
                - --playlists
                - "Smart Toons"
              volumeMounts:
                - name: config
                  mountPath: /config
          volumes:
            - name: config
              secret:
                secretName: plex-jobs
                defaultMode: 0775
                items:
                  - key: config.ini
                    path: config.ini
