---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager-certificates
  namespace: &namespace kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: raw
      version: v0.3.2
      sourceRef:
        kind: HelmRepository
        name: dysnix-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: cert-manager-issuers
      namespace: *namespace
  values:
    resources:
      - apiVersion: cert-manager.io/v1
        kind: Certificate
        metadata:
          name: "${SECRET_PUBLIC_DOMAIN/./-}"
          namespace: *namespace
        spec:
          secretName: "${SECRET_PUBLIC_DOMAIN/./-}-tls"
          issuerRef:
            name: letsencrypt-production
            kind: ClusterIssuer
          commonName: "${SECRET_PUBLIC_DOMAIN}"
          dnsNames:
            - "${SECRET_PUBLIC_DOMAIN}"
            - "*.${SECRET_PUBLIC_DOMAIN}"
