---
name: "Meta: Labeler"

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main

jobs:
  labeler:
    name: Labeler
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: tibdex/github-app-token@021a2405c7f990db57f5eae5397423dcc554159c # renovate: tag=v1.7.0
        id: generate-token
        with:
          app_id: "${{ secrets.BOT_APP_ID }}"
          private_key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Labeler
        uses: actions/labeler@9fcb2c2f5584144ca754f8bfe8c6f81e77753375 # v4.1.0
        with:
          configuration-path: .github/labeler.yaml
          repo-token: "${{ steps.generate-token.outputs.token }}"
